# Generated by Django 4.1.7 on 2023-06-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('d_description', models.CharField(max_length=255)),
                ('c_description', models.CharField(max_length=255)),
                ('idempotenceToken', models.CharField(max_length=15)),
                ('transferState', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('DELETED', 'DELETED')], max_length=10)),
                ('c_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_credits', to='bank_app.account')),
                ('d_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_debits', to='bank_app.account')),
            ],
        ),
    ]
