# Generated by Django 3.1.4 on 2023-05-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_auto_20230506_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
